### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by aditi48n** [UBC-MDS/chocolate_rating#28]
Congratulations on finishing milestone 1! We can see you put a lot of work into this project, nice work! Below we list some specific feedback you can use to improve your project. We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.

Code of Conduct.md
- [x] A list of consequences for unacceptable behaviour -0.5
**Comment:** Consequences are mentioned under procedure for reporting and dealing with unacceptable behaviour and not as a list in a separate section. 

CONTRIBUTING.md
- [x] Contributing documentation should reflect all the ways people can contribute to the project (core members, who should be working in a GitHub flow workflow involving branching in the main project repo and opening PR's, as well as arms-length contributors, who more likely may have to fork the repo before submitting a PR). -1
**Comment:** Core teams contribution workflow is not mentioned. 

Project proposal
- [x] The question should be specific enough. For example, "Is eating a healthier diet better for you?" is written ambiguously. What do you mean by "healthier diet"? . Instead, "Does eating at least 5 servings per day of fresh fruits and vegetables lead to fewer upper respiratory tract infections (colds)?" is clearer and more concrete. -1 reasoning
**Comment:** Questions are too many and not specific. A better way of framing your question would be- Does manufacturer, country of bean origin, cocoa percent etc., influence the preference for one chocolate over the other? This or something on similar lines. Be more specific. 

- [x] Clarity of README could be improved through additional proofreading (i.e., spelling and grammatical errors are present). -1
**Comment:** Document has grammatical errors. Proofread going forward. 

Exploratory data analysis in a literate code document
- [ ] There are not figure captions. -2 viz
**Comment:** All figures should have a title or caption so it is easier to go through them. 
- [ ] There figure captions for the tables should be above the table. -1 viz
**Comment:** Captions for the table are missing. 
- [x]  Dependencies (or link pointing to list elsewhere) is missing from the README.md file. The dependency list should include docopt package. -0.5
**Comment:** Docopt dependency missing from list

Expectations
- [x]  All contributions are expected to go through code review via a pull-request. A branch protection rule should be set in the main branch. There shouldn't exist commits in the main branch, except the ones created when you merged branches. -1
**Comment:** Other commits on main branch other than the ones created for merge.

**Comment by robindhillon1** [comment]
Hi Aditi, thank you for the feedback. It's greatly appreciated for the upcoming milestones. However, I did want to bring up some issues with the grading. These are described below:
- Contributing: "Core teams contribution workflow is not mentioned". This is not mentioned anywhere and I followed several official examples that were provided to make sure everything was included. 
- Readme: "Document has grammatical errors. Proofread going forward." Sorry but I disagree. We all proofread and there are no glaring mistakes. I feel this is very subjective and not fair to take marks off for milestone 1.
- No figure titles: This is EDA for ourselves, we don't really need titles.
- No table captions: Again, this is EDA for ourselves, we don't need titles and we were not told to do so either.

**Comment by aditi48n** [comment]
Hi Robin, 

Thank you for message. I can give you an explanation for my grading, if you still disagree I can revisit and see what to do. Does that sound reasonable? 

For the first point you have raised, I have already sent a message to Florencia as it was in the grading rubric but not mentioned as part of the instructions so it didnt seem fair to deduct marks. I am yet to hear from her but as soon as I do, I will adjust the grade. 

I have provided feedback and grades based on a rubric set by the professor. The rubric included grammatical errors so teams can correct them going forward. I cannot pinpoint to all instances but one instance from your readme is the following sentence- "Initial exploratory data analysis (EDA) will include investigating the data such as finding and replacing any missing values, and tables that summarize key info such as column datatypes and generate descriptive statistics will also be created." 

For the last two points, the instructions for the milestone clearly state the requirement for captions. https://pages.github.ubc.ca/MDS-2022-23/DSCI_522_dsci-workflows_students/materials/assignments/milestone1.html
If you look under section 4. Exploratory data analysis in a literate code document, point 3- Create at least two plots and one table. Add [figure captions properly](https://clauswilke.com/dataviz/figure-titles-captions.html) for the table and for the plot. 

Thank you.

**Comment by robindhillon1** [comment]
Ah, I must've missed the captions part, I apologize. But I do feel that sentence is fine; a bit long, but grammatically correct. And if it is indeed incorrect, -1 for just one sentence is too much I feel.

**Comment by markusnam** [comment]
Also regarding **"All contributions are expected to go through code review via a pull-request. A branch protection rule should be set in the main branch. There shouldn't exist commits in the main branch, except the ones created when you merged branches."**,
actually we explicitly asked if it is necessary to do milestone 1 in a "individual branch approach", Florencia said it's ok to do it on the main branch directly for milestone 1. That's why we took this convenient way to make minor changes.

**Comment by aditi48n** [comment]
Right on! let me go back and take a look at both those bits and also have a quick chat with Florencia. Don't worry about the final grade for this Milestone. I will make changes accordingly.

**Comment by robindhillon1** [comment]
Hi @aditi48n, I was going through the feedback to improve our project before the deadline of milestone 4, and I had a few questions/required some clarifications:
- "Consequences are mentioned under procedure for reporting and dealing with unacceptable behaviour and not as a list in a separate section." I'm not sure I understand what you're referring to. We followed the template provided by Tiffany's repo here: https://github.com/ttimbers/breast_cancer_predictor/blob/master/CODE_OF_CONDUCT.md. Could you please clarify?
- Core teams contribution workflow is not mentioned. Could you also explain this so I can fix it?

**Comment by danielramandi** [comment]
Issues with CoC and CONTRIBUTING.md was resolved in Canvas. You can check the boxes as done.
