### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by muntakimrafi** [UBC-MDS/chocolate_rating#51]
Congratulations on finishing milestone 2! I loved the workflow of the project. 

- [ ] Analysis code is satisfactory. 

- [ ] Version controlling was satisfactory. 

- [ ] The project file and directory structure organization look good. I ran the code and recreated the analysis in the results directory. However, I was not able to create the final analysis report. The error I got was

> processing file: chocolate_rating.Rmd
  |.....                                                                 |   7%
  ordinary text without R code
  |.........                                                             |  13%
label: setup (with options) 
List of 1
 $ include: logi FALSE
Quitting from lines 15-20 (chocolate_rating.Rmd) 
Error in library(kableExtra) : there is no package called 'kableExtra'
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> library
Execution halted

Also, the instruction to move to RStudio to create the analysis report is not convenient. Please address this. 

- [ ] Submission expectations were met.

**Comment by robindhillon1** [comment]
Hi Abdul,

We just had a meeting with Florencia and Daniel for like an hour trying to fix these issues.
1. `kableExtra` is a built-in R package that was demonstrated during lecture and we were led to believe that everyone has it pre-installed. We did not know that some individuals might not have it (it seems you didn't); when testing on our own personal computers, we did not encounter this error. 
2. The instruction to move to RStudio to create the analysis report is inconvenient, but that is because we were having issues with `pandoc`. As Florencia told us today, these are relatively new issues that can take time to debug and fix. We were not able to do so before the deadline, and hence we made the decision to move to RStudio for the report creation. Furthermore, we also brought up this issue on the 522 slack channel without any resolution. See post here: https://ubc-mds.slack.com/archives/C24HUNRJL/p1669500698193449

If you can't access the post, I'm attaching a screenshot below.

![image](https://user-images.githubusercontent.com/86622951/204935543-f40a2da2-ead9-4ae9-b5e2-c799739f9867.png)

So ultimately, we believe the -5 for these errors (which were out of our control) is a bit unfair since we did everything properly to the best of our ability. We're actively working on fixing these errors and should have a proper resolution soon. Hope you understand. 

Thanks for your time,
Robin

**Comment by muntakimrafi** [comment]
Hello Robin,

The course is about reproducibility. You are supposed to make your repo reproducible. You should never assume what packages the TA might have already installed on their laptops. If your repo needs to use some specific library from R, your conda environment should install them as well. I never used my own environment for evaluating your project. I made a new environment using the .yml file you provided and then tested it in that environment. I would suggest you guys follow the same procedure for in-house testing as this is how people will try to reproduce your work. 
In my opinion, it was fair to deduct 5 marks as it would not be fair to other projects who got everything right. I wish you guys best of luck.

**Comment by markusnam** [comment]
Hi Rafi,

Let me describe what I did before submission and see what can be done better regarding the missing `kableExtra` issue.
1. Update the `.yaml` based on our understanding about the required packages.
2. Remove environment `522` from my laptop.
3. Fresh create `522` from the `.yaml`.
4. Run the commands illustrated in `README.md` one by one and check the output.
Everything was alright, no error, no issue, so we thought it was good to go.

Is the above regarded as brand new and clean environment? If no, what should we do in order to achieve that?

I understand your point but if viewing from our angle (not an expert in conda / environment thing), how could we discover something would go wrong as we have already done whatever we know from scratch to simulate a new user who is going to reproduce the output?

Your advice is very much appreciated. I believe my team can definitely learn from this case.

Regards,
Markus

**Comment by muntakimrafi** [comment]
Hello Markus,

Yes, it would be a new and clean environment. If you are doing rigorous checks like that, your code should be reproducible across all systems. Not sure what went wrong. Maybe ask me in the lab, and we can discuss this further. 

I appreciate the effort you and your team put into making your code reproducible.

**Comment by robindhillon1** [comment]
@muntakimrafi we looked for you in the lab yesterday but didn't see you. When/where can we talk about this?
