### ISSUE TITLE
Milestone 4 - Feedback

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/chocolate_rating#88]
**Congratulations on finishing milestone 4!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.

## Dependency diagram of the Makefile (max 5 points)
Good job!
### Dockerfile

- [x] The base image the `Dockerfile` uses in the `FROM` statement should have it's version pinned. 
Failing to do this, means that each time the Docker image is built in the future, 
the latest version of the base image will be used.
The latest version of the base image will very likely change over time, 
and failing to do this will lead to the container not being able to be reproducibly built in the future. **-2 quality**
**Comments:** Missing version for "FROM continuumio/miniconda3"

- [x] The dependencie versions are not pinned. **-2 quality**
**Comments:** Version number is not pinned for all dependencies
- [x] There are not GitHub Actions workflows or there are not working properly. **-5 accuracy**
**Comments:** Github Action was not included

###  Analysis can be run reproducibly using documentation provided in the README

- [x] Clearly specify usage instructions to the point a user could copy and paste them and they would work. 
If a specific value needs to be inserted (e.g., volume mounting, port forwarding, tag version - which should be specified, as relying on `latest` is unreliable for many reasons, etc) 
suggest the most reasonable value and provide the list 
(or link to a list) of alternative options. **-2 mechanics**
**Comment** Should include tag for docker pull (ie docker pull eyrexh/chocolate_rating_docker:v0.12.0)

## Final Submission: Improve the project based on the feedback received
Good job!

### Expectations
Good job!

**Comment by eyrexh** [comment]
Hi Glenn,

I'd like to address some issues based on your feedback.

1. "The base image the Dockerfile uses in the FROM statement should have its version pinned." We didn’t recall Florencia mentioning anything about that; our golden reference `breast_cancer` also does not have that! https://github.com/ttimbers/breast_cancer_predictor
2. "The dependent versions are not pinned. -2 quality
Comments: The version number is not pinned for all dependencies" Same as before, neither Florencia mentioned nor our reference `brease_cancer` does have it.
3. The workflow is in my own repo. We did not include the GitHub Action workflow in our main `chocolate_rating` repo because `breast_cancer` does not have one too!  For you to check, below is the workflow link:
https://github.com/eyrexh/chocolate_rating_docker/blob/main/.github/workflows/publish-chocolate.yml
We have double-checked with Florencia last Friday and she said everything works perfectly. The rubrics she provided for milestone 4 also do not mention anything about "including the workflow in your own repo". If that is the requirement, I can add it right now in the repo.
4. "Should include a tag for docker pull". Again, we have no clue that is required since we have not been taught to do so.

Thank you for your time.
Regards,
Eyre

**Comment by Glenn032787** [comment]
Hi Eyre,

The breast_cancer repository is simply an example of a data science workflow repository. You are ultimately being marked based on the rubric and instructions for the assignment, not how similar your project is to the breast_cancer repository. 

Comment 1,2,4) This course has a focus on reproducibility and the idea of specifying version number for users in the future to reproduce your research is consistently mentioned throughout the lectures and past milestone. As shown [here](https://pages.github.ubc.ca/fdandrea/522-lecture8/522-lecture8.html#/take-home-message-what-to-use-for-your-project)
Comment 3) GitHub actions was clearly specified in the milestone 4 instructions: `use GitHub Actions to build your Docker image from your Dockerfile`. I am not sure how you expected us to mark this if you did not include this in the Github repo you submitted on canvas. 

I cannot give you points if you clearly did not do the specified tasks in the instructions and rubric. If you have an issue with the rubric, you could speak to Florencia.

**Comment by robindhillon1** [comment]
Hi Glenn, we're not given a rubric so how can we follow it? Thanks for your time, we're contacting Florencia as you suggest.

**Comment by markusnam** [comment]
Hi Glenn,
May I know the expectation on GitHub Action Workflow? What should be done in order to get full mark for that part? We would like to understand the best practice so that we can follow that in the future.
Let me briefly explain how we did that part for Milestone 4. Then you may comment on which part could be done better.
(a) Our main project repository is `chocolate_rating` which stores all scripts, image files and report files.
(b) We created a separate repository solely for GitHub Action Workflow because we noticed that if we did the workflow on `chocolate_rating`, every single change (even a minor change in README.md) in the repository would trigger a generation of a new Docker Image. We thought this is not desirable and also noticed the `breast_cancer` repo also does not come with the action workflow folder.
